# Generated by Django 4.1.2 on 2023-04-15 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blancos',
        ),
        migrations.DeleteModel(
            name='Cocina',
        ),
    ]
